# Generated by Django 2.2.5 on 2019-09-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Singer', models.CharField(max_length=100)),
                ('Lyrics', models.TextField()),
                ('Audio', models.FileField(upload_to='')),
                ('Thumbnail', models.ImageField(upload_to='')),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
    ]
