# Generated by Django 2.2.5 on 2019-09-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0002_auto_20190925_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsdata',
            name='Thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
